version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slim-app
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t public
    ports:
      - "8080:8080"
    depends_on:
      - composer

  composer:
    image: composer:2
    container_name: slim-composer
    volumes:
      - ./:/app
    entrypoint: ["composer"]

  nginx:
    image: nginx:alpine
    container_name: slim-nginx
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app
