services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slim-app
    volumes:
      - ./src:/var/www/html
      - ./docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    working_dir: /var/www/html
    command: >
      bash -c "mkdir -p /var/www/html/var 
      && chmod -R 777 /var/www/html/var 
      && php-fpm"
    ports:
      - "9000:9000"
      - "9003:9003"
    environment:
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - composer

  composer:
    image: composer:2
    container_name: slim-composer
    volumes:
      - ./src:/app
    working_dir: /app
    command: install

  nginx:
    image: nginx:alpine
    container_name: slim-nginx
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app
