### upload from url
POST {{host}}/images/upload-url?url=https://www.pragmoon.cz/uploaded_images/thumb/laura-a-jeji-tygri.jpg&
    token={{securityToken}}

### get health
GET {{host}}/images/health/e6a8d25da0b679ce3eedc18ac7302036.jpg

### get original
GET {{host}}/images/original/e6a8d25da0b679ce3eedc18ac7302036.jpg

### PROD get resized
GET {{host}}/images/resized/e6a8d25da0b679ce3eedc18ac7302036.jpg?type=crop&width=150&height=150&
    token=5dec611e
